defaults:
  - dataset: default
  - telemetry: default
  - training: default
  - quantization: default
  - validation: default
  - export: default
  - visualization: default
  - package: default
  - _self_
